threshold: 10
model: true
errors:
  - gazrafail@gmail.com
alerts:
  suppress:
    - on-found-puzzle
    - on-lost-puzzle
    - on-scope
  github:
    - illusior
format:
  - short-title
  - title-length=100
tags:
  - pdd
  - bug
