services:
  base:
    build:
      context: ./../
      dockerfile: ./.docker/Dockerfile
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      DOCKER_INTERNAL_HOST: ${DOCKER_INTERNAL_HOST:-0.0.0.0}
      DOCKER_INTERNAL_PORT: ${DOCKER_INTERNAL_PORT:-4200}
